// CPC Palette with HW values
// Generated by mkts_om v0.5.20210614
// Copyleft 2017-2021 by The Mojon Twins

const unsigned char my_inks [] = {
	0x04, // FF000080
	0x14, // FF000000
	0x0B, // FFFFFFFF
	0x0A, // FFFFFF00
	0x0C, // FFFF0000
	0x0E, // FFFF8000
	0x1B, // FF80FFFF
	0x00, // FF808080
	0x1C, // FF800000
	0x16, // FF008000
	0x18, // FF800080
	0x1F, // FF8080FF
	0x17, // FF0080FF
	0x13, // FF00FFFF
	0x1E, // FF808000
	0x03  // FFFFFF80
};

