' ene2h.bas v0.8.20250311-v4

' Commands first draft
' CMD=C,T,O,V where C = command, T = type, O = output member, V = value
'
' First version CMD=S,T,O,V (SET), example CMD=S,15,Y2,0, sets Y2=0 for t=15

' Have to parse & encode commands into a numeric array.
' Then 'Run' the array for each enemy processed.

#include "mtparser.bi"
#include "cmdlineparser.bi"

Type CMD
	cmd As String * 1
	t As Integer
	o As String * 2
	v As Integer
End Type

Sub usage
	Print
	Print "$ ene2h.exe enems.ene|empty=W,H,N enems.h [2bytes] [dslight|dsall] [compacted] [indexed] [CMD=C,T,O,V] [marrullers]"
	Print
	Print "empty en vez de enems.ene generará todo a 0 contando WxH con N enems"
	Print
	Print "2bytes (optional) - support really old .ene files which stored the hotspots"
	Print "    2 bytes each instead of 3 bytes.  As a rule of thumb: "
	Print "    * .ene file created with ponedor.exe -> 3 bytes."
	Print "    * .ene file created with colocador.exe for MK1 -> 2 bytes."
	Print
	Print "dslight (optional) - x1/x2 and y1/y2 are usually switched to make sure 1<2."
	Print "    If 'dslight' is specified, only types 1-4 and 7-14 are switched."
	Print
	Print "dsall (optional) - Like dslight, but only types 1-4 are switched."
	Print
	Print "compacted (optional) - pack x1, y1 and x2, y2 in 1 byte XY each."
	Print
	Print "indexed (optional) - stores only existing enemies + an index."
	Print
	Print "marrullers (optional) - enems 11-14 are marrullers & will make x1=1, y1=1, x2=13, y2=8"
End Sub

Function inCommand (spec As String) As Integer
	Dim As Integer res, i

	i = 0: res = 0

	Do
		If Command (i) = "" Then Exit Do
		If Command (i) = spec Then res = -1: Exit Do
		i = i + 1
	Loop

	Return res
End Function

Const DS_NONE = 0
Const DS_LIGHT = 1
Const DS_ALL = 2

Dim As Integer use2bytes, dontswitch
Dim As Integer fIn, fOut, i, j, k, mapPants
Dim As uByte d, mapW, mapH, nEnems
Dim As uByte t, a, b, xx, yy, mn, x, y, s1, s2, xy, whichCommand
Dim As Integer typeCounters (255)
Dim As Integer enTypeCounters (255)
Dim As String Dummy, cmm
Dim As Integer sx, sy, equals
Dim As Integer compacted
Dim As Integer marrullers
Dim As Integer indexed
Dim As Integer coords (16)
Dim As Integer outX, outY, outX1, outX2, outY1, outY2, outMX, outMY, outT
Dim As CMD cmds (31)
Dim As Integer cmdIndex
Dim As String tokens (16)
Dim As Integer enoffsIndex(999)
Dim As Integer nonEmptyEnems
Dim As Integer first
Dim As Integer empty

Print "ene2h.bas v0.8.20250311-v4 ";

sclpParseAttrs

If Command (2) = "" Then usage: End

For i = 0 To 255
	enTypeCounters (i) = 0
	typecounters (i) = 0
Next i

use2bytes = inCommand ("2bytes")

If inCommand ("dsall") Then 
	dontswitch = DS_ALL
ElseIf inCommand ("dslight") Then
	dontswitch = DS_LIGHT
Else
	dontswitch = DS_NONE
End If

compacted = inCommand ("compacted")

marrullers = inCommand ("marrullers")

indexed = inCommand ("indexed")

empty = sclpGIsDef ("empty")
If empty Then
	parseCommaSeparatedString sclpGetValue ("empty"), tokens ()
	mapW = Val (tokens (0))
	mapH = Val (tokens (1))
	nEnems = Val (tokens (2))
End If 

' Look for & parse CMDs
i = 3
cmdIndex = 0
While (Command (i) <> "")
	If Len (Command (i)) > 4 And Left (Command (i), 4) = "CMD=" Then
		parseCommaSeparatedString Right (Command (i), Len (Command (i)) - 4), tokens ()
		cmds (cmdIndex).cmd = tokens (0)
		cmds (cmdIndex).t = Val (tokens(1))
		cmds (cmdIndex).o = tokens(2)
		cmds (cmdIndex).v = Val (tokens(3))
		cmdIndex = cmdIndex + 1
	End If
	i = i + 1
Wend

If cmdIndex > 0 Then Print "~ " & cmdIndex & " commands found ";

If Not empty Then 
	fIn = FreeFile
	Open Command (1) For Binary As #fIn
End If 

fOut = FreeFile
Open Command (2) For Output As #fOut

' Header
If Not empty Then 
	dummy = Input (256, fIn)
	Get #fIn, , d: mapW = d
	Get #fIn, , d: mapH = d
	Get #fIn, , d: Get #fIn, , d
	Get #fIn, , d: nEnems = d
End If

mapPants = mapW * mapH

Print #fOut, "// MTE MK1 (la Churrera) v4"
Print #fOut, "// Copyleft 2010-2014, 2020-2025 by the Mojon Twins"
Print #fOut, ""

Print #fOut, "// Generated by ene2h.exe from " & Command (1)
Print #fOut, "// Copyleft 2010, 2017, 2020-2025 by The Mojon Twins"
Print #fOut, ""

Print #fOut, "typedef struct {"
Print #fOut, "	unsigned char x, y;"
If compacted Then
	Print #fOut, "	unsigned char xy1, xy2;"
Else
	Print #fOut, "	unsigned char x1, y1, x2, y2;"
End If

Print #fOut, "	signed char mx, my;"
Print #fOut, "	signed char t;"
Print #fOut, "#if ((defined PLAYER_CAN_FIRE || defined ENABLE_SWORD) && ENEMS_LIFE_GAUGE > 1) || defined FORCE_ENEMS_LIFE"
Print #fOut, "	unsigned char life;"
Print #fOut, "#endif"
Print #fOut, "} MALOTE;"
Print #fOut, ""
Print #fOut, "MALOTE malotes [] = {"

first = -1
For i = 1 To mapPants
	Print #fOut, "	// Pantalla " & (i-1)
	enoffsIndex (i-1) = nonEmptyEnems
	For j = 1 To nEnems

		If empty Then 
			t = 0
			x = 0
			y = 0
			xx = 0
			yy = 0
			mn = 0
			s1 = 0
			s2 = 0
		Else
			Get #fIn, , t
			Get #fIn, , x
			Get #fIn, , y
			Get #fIn, , xx
			Get #fIn, , yy 
			Get #fIn, , mn
			Get #fIn, , s1
			Get #fIn, , s2
		End If

		outX = 16*x: outY = 16*y

		enTypeCounters (t) = enTypeCounters (t) + 1

		' New logic to ensure x1 < x2, y1 < y2
		sx = Sgn (xx - x)
		sy = Sgn (yy - y)

		If dontswitch = DS_NONE Or _ 
			(dontswitch = DS_LIGHT And (t < 5 Or (t > 6 And t < 15))) Or _ 
			(dontswitch = DS_ALL And t < 5) Then
			If x > xx Then Swap x, xx 
			If y > yy Then Swap y, yy
		End If

		outX1 = 16*x: outY1 = 16*y
		outX2 = 16*xx: outY2 = 16*yy
		outMX = mn*sx: outMY = mn*sy
		outT = t

		' Marrullers
		If marrullers And t >= 11 And t <= 14 Then 
			outX1 = 16: outX2 = 13 * 16
			outY1 = 16: outY2 = 8 * 16
		End If

		' Run commands
		For k = 0 To cmdIndex - 1
			If cmds (k).t = t Then 
				Select Case cmds (k).cmd
					Case "S":
						' Setter
						Select Case cmds (k).o
							Case "X": outX = cmds (k).v
							Case "Y": outY = cmds (k).v
							Case "X1": outX1 = cmds (k).v: x = cmds (k).v
							Case "Y1": outY1 = cmds (k).v: y = cmds (k).v
							Case "X2": outX2 = cmds (k).v: xx = cmds (k).v
							Case "Y2": outY2 = cmds (k).v: yy = cmds (k).v
							Case "MX": outMX = cmds (k).v
							Case "MY": outMY = cmds (k).v
							Case "T": outT = cmds (k).v
						End Select
				End Select
			End If
		Next k

		If Not indexed Or outT <> 0 Then

			Print #fOut, " 	{";
			Print #fOut, "" & (outX) & ", " & (outY) & ", ";		' x y
			
			If compacted Then
				Print #fOut, "0x" & Hex (16*(outX1/16) + (outY1/16), 2) & ", ";		' xy1
				Print #fOut, "0x" & Hex (16*(outX2/16) + (outY2/16), 2) & ", ";		' xy2
			Else
				Print #fOut, "" & (outX1) & ", " & (outY1) & ", ";		' x1 y1
				Print #fOut, "" & (outX2) & ", " & (outY2) & ", ";		' x2 y2
			End If
			
			Print #fOut, "" & (outMX) &  ", "; 		' mx
			Print #fOut, "" & (outMY) & ", "; 		' my
			
			Print #fOut, "" & (outT); 								' t
			Print #fOut, "}";

			If i < mapPants Or j < nEnems Then Print #fOut, "," Else Print #fOut, ""

			nonEmptyEnems = nonEmptyEnems + 1
		End If
	Next j
	Print #fOut, ""
Next i
If indexed Then
	If nonEmptyEnems < mapPants * nEnems Then Print #fOut, "	{0xff}"
End If
Print #fOut, "};"
Print #fOut, ""

' New: Index
If indexed Then
Print #fOut, "// enoffs index, contains enoffs for each screen"
Print #fOut, "unsigned char enoffs_index [] = {"
k = 0

For j = 0 To mapH - 1
	Print #fOut, "	";
	For i = 0 To mapW - 1
		Print #fOut, "" & enoffsIndex(k);: k = k + 1
		Print #fOut,  ", ";
	Next i
	Print #fOut, "" 
Next j
Print #fOut, "	" & nonEmptyEnems & " // <- total number of enems to make coding easier"

Print #fOut, "};"
Print #fOut, "" 
End If

For i = 0 To 255
	If (enTypeCounters (i) > 0 Or i <= 7) And i <> 4 Then
		Print #fOut, "#define N_ENEMS_TYPE_" & i & " " & enTypeCounters (i)
	End If
Next i

Print #fOut, ""
Print #fOut, "// This is output the way it worked originally, please modify if you need"
Print #fOut, "// You may want to add type 5 or 6's below."
Print #fOut, "#define BADDIES_COUNT (N_ENEMS_TYPE_1+N_ENEMS_TYPE_2+N_ENEMS_TYPE_3)"

Print #fOut, ""
If Indexed Then 
	Print #fOut, "#define TOTAL_EXISTING_ENEMS " & nonEmptyEnems
Else
	Print #fOut, "#define TOTAL_EXISTING_ENEMS " & (mapPants * nEnems)
End If

Print #fOut, ""
Print #fOut, "typedef struct {"
Print #fOut, "	unsigned char xy, tipo, act;"
Print #fOut, "} HOTSPOT;"
Print #fOut, ""
Print #fOut, "HOTSPOT hotspots [] = {"

For i = 1 To mapPants
	If empty Then
		xy = 0
		t = 0
	Else 
		If use2bytes Then
			Get #fIn, , xy
			Get #fIn, , t
		Else
			Get #fIn, , x
			Get #fIn, , y
			Get #fIn, , t
			xy = (x Shl 4) Or (y And 15)
		End If
	End If

	typeCounters (t) = typeCounters (t) + 1

	Print #fOut, "	{";
	Print #fOut, xy; ", "; t; ", 0";
	Print #fOut, "}";

	If i < mapPants Then Print #fOut, ", " Else Print #fOut, ""
Next i

Print #fOut, "};"
Print #fOut, ""

For i = 0 To 255
	If typeCounters (i) <> 0 Or i < 8 Then
		Print #fOut, "#define N_HOTSPOTS_TYPE_" & i & " " & typeCounters (i)
	End If
Next i

Print #fOut, ""

Close


Print " ~ DONE"
