// CPC Palette with HW values
// Generated by mkts_om v0.11.20250501
// Copyleft 2017-2025 by The Mojon Twins

#asm
	.inks0
		ld  b, 0x7f
		ld  a, 0
		out (c), a
		ld  a, 0x45	// 0b0100000 OR 5 (FFFF0080)
		out (c), a
		ld  a, 1
		out (c), a
		ld  a, 0x58	// 0b0100000 OR 18 (FF800080)
		out (c), a
		ld  a, 2
		out (c), a
		ld  a, 0x4E	// 0b0100000 OR E (FFFF8000)
		out (c), a
		ld  a, 3
		out (c), a
		ld  a, 0x43	// 0b0100000 OR 3 (FFFFFF80)
		out (c), a
		ld  a, 4
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 5
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 6
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 7
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 8
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 9
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 10
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 11
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 12
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 13
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 14
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ld  a, 15
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ret
#endasm

