// CPC Palette with HW values
// Generated by mkts_om v0.10.20250415
// Copyleft 2017-2025 by The Mojon Twins

#asm
	.inks2
		ld  b, 0x7f
		ld  a, 0
		out (c), a
		ld  a, 0x45	// 0b0100000 OR 5 (FFFF0080)
		out (c), a
		ld  a, 1
		out (c), a
		ld  a, 0x5C	// 0b0100000 OR 1C (FF800000)
		out (c), a
		ld  a, 2
		out (c), a
		ld  a, 0x4A	// 0b0100000 OR A (FFFFFF00)
		out (c), a
		ld  a, 3
		out (c), a
		ld  a, 0x4B	// 0b0100000 OR B (FFFFFFFF)
		out (c), a
		ret
#endasm

