// CPC Palette with HW values
// Generated by mkts_om v0.10.20250415
// Copyleft 2017-2025 by The Mojon Twins

#asm
	.my_inks
		ld  b, 0x7f
		ld  a, 0
		out (c), a
		ld  a, 0x5C	// 0b0100000 OR 1C (FF800000)
		out (c), a
		ld  a, 1
		out (c), a
		ld  a, 0x54	// 0b0100000 OR 14 (FF000000)
		out (c), a
		ld  a, 2
		out (c), a
		ld  a, 0x56	// 0b0100000 OR 16 (FF008000)
		out (c), a
		ld  a, 3
		out (c), a
		ld  a, 0x5B	// 0b0100000 OR 1B (FF80FFFF)
		out (c), a
		ret
#endasm

