// CPC Palette with HW values
// Generated by mkts_om v0.6.20210822
// Copyleft 2017-2021 by The Mojon Twins

const unsigned char my_inks_1 [] = {
	0x14, // FF000000
	0x18, // FF800080
	0x1F, // FF8080FF
	0x03, // FFFFFF80
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B  // FFFFFFFF
};

