// CPC Palette with HW values
// Generated by mkts_om v0.6.20210822
// Copyleft 2017-2021 by The Mojon Twins

const unsigned char my_inks [] = {
	0x14, // FF000000
	0x15, // FF0000FF
	0x05, // FFFF0080
	0x03, // FFFFFF80
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14, // FF000000
	0x14  // FF000000
};

