// CPC Palette with HW values
// Generated by mkts_om v0.9.20230331
// Copyleft 2017-2023 by The Mojon Twins

const unsigned char my_inks [] = {
	0x16, // FF008000
	0x14, // FF000000
	0x0E, // FFFF8000
	0x03, // FFFFFF80
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B  // FFFFFFFF
};

