// CPC Palette with HW values
// Generated by mkts_om v0.11.20250501
// Copyleft 2017-2025 by The Mojon Twins

#asm
	.pal_general
		ld  b, 0x7f
		ld  a, 0
		out (c), a
		ld  a, 0x54	// 0b0100000 OR 14 (FF000000)
		out (c), a
		ld  a, 1
		out (c), a
		ld  a, 0x5C	// 0b0100000 OR 1C (FF800000)
		out (c), a
		ld  a, 2
		out (c), a
		ld  a, 0x40	// 0b0100000 OR 0 (FF808080)
		out (c), a
		ld  a, 3
		out (c), a
		ld  a, 0x4E	// 0b0100000 OR E (FFFF8000)
		out (c), a
		ret
#endasm

