// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by ene2h.exe from ..\enems\enems.ene
// Copyleft 2010, 2017 by The Mojon Twins

typedef struct {
	unsigned char x, y;
	unsigned char x1, y1, x2, y2;
	char mx, my;
	char t;
#ifdef PLAYER_CAN_FIRE
	unsigned char life;
#endif
} MALOTE;

MALOTE malotes [] = {
	// Pantalla 0
 	{112, 16, 112, 16, 128, 16, 0, 0, 6},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 1
 	{112, 128, 112, 128, 48, 128, -1, 0, 2},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 2
 	{48, 16, 48, 16, 48, 96, 0, 2, 3},
 	{176, 16, 176, 16, 176, 96, 0, 2, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 3
 	{176, 128, 176, 128, 16, 128, -2, 0, 2},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 4
 	{16, 96, 16, 96, 128, 128, 1, 1, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 5
 	{0, 16, 0, 16, 16, 64, 1, 1, 3},
 	{144, 80, 144, 80, 32, 80, -1, 0, 1},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 6
 	{96, 48, 96, 48, 128, 80, 1, 1, 3},
 	{32, 16, 32, 16, 32, 128, 0, 2, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 7
 	{144, 16, 144, 16, 144, 96, 0, 2, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 8
 	{80, 64, 80, 64, 112, 64, 1, 0, 2},
 	{144, 16, 144, 16, 144, 80, 0, 1, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 9
 	{144, 32, 144, 32, 160, 96, 1, 1, 1},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 10
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 11
 	{224, 128, 224, 128, 80, 128, -2, 0, 1},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 12
 	{144, 16, 144, 16, 144, 144, 0, 1, 3},
 	{80, 32, 80, 32, 80, 128, 0, 1, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 13
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 14
 	{16, 80, 16, 80, 160, 80, 2, 0, 1},
 	{192, 16, 192, 16, 192, 80, 0, 1, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 15
 	{112, 32, 112, 32, 80, 32, -1, 0, 2},
 	{176, 16, 176, 16, 160, 128, -1, 1, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 16
 	{144, 16, 144, 16, 160, 128, 1, 1, 3},
 	{96, 16, 96, 16, 96, 80, 0, 1, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 17
 	{112, 32, 112, 32, 128, 128, 2, 2, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0},

	// Pantalla 18
 	{144, 32, 144, 32, 80, 32, -1, 0, 2},
 	{48, 16, 48, 16, 64, 48, 1, 1, 3},
 	{48, 64, 48, 64, 48, 112, 0, 1, 3},

	// Pantalla 19
 	{128, 128, 128, 128, 16, 128, -1, 0, 1},
 	{48, 16, 48, 16, 64, 112, 1, 1, 3},
 	{0, 0, 0, 0, 0, 0, 0, 0, 0}

};

#define N_ENEMS_TYPE_0 31
#define N_ENEMS_TYPE_1 5
#define N_ENEMS_TYPE_2 5
#define N_ENEMS_TYPE_3 18
#define N_ENEMS_TYPE_5 0
#define N_ENEMS_TYPE_6 1
#define N_ENEMS_TYPE_7 0

// This is output the way it worked originally, please modify if you need
// You may want to add type 5 or 6's below.
#define BADDIES_COUNT (N_ENEMS_TYPE_1+N_ENEMS_TYPE_2+N_ENEMS_TYPE_3)

typedef struct {
	unsigned char xy, tipo, act;
} HOTSPOT;

HOTSPOT hotspots [] = {
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{99, 2, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{166, 2, 0}, 
	{0, 0, 0}, 
	{228, 2, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}
};

#define N_HOTSPOTS_TYPE_0 17
#define N_HOTSPOTS_TYPE_1 0
#define N_HOTSPOTS_TYPE_2 3
#define N_HOTSPOTS_TYPE_3 0
#define N_HOTSPOTS_TYPE_4 0
#define N_HOTSPOTS_TYPE_5 0
#define N_HOTSPOTS_TYPE_6 0
#define N_HOTSPOTS_TYPE_7 0

