// CPC Palette with HW values
// Generated by mkts_om v0.11.20250501
// Copyleft 2017-2025 by The Mojon Twins

#asm
	.pal_hud
		ld  b, 0x7f
		ld  a, 0
		out (c), a
		ld  a, 0x4C	// 0b0100000 OR C (FFFF0000)
		out (c), a
		ld  a, 1
		out (c), a
		ld  a, 0x5A	// 0b0100000 OR 1A (FF80FF00)
		out (c), a
		ld  a, 2
		out (c), a
		ld  a, 0x5B	// 0b0100000 OR 1B (FF80FFFF)
		out (c), a
		ld  a, 3
		out (c), a
		ld  a, 0x54	// 0b0100000 OR 14 (FF000000)
		out (c), a
		ret
#endasm

