// CPC Palette with HW values
// Generated by mkts_om v0.10.20250415
// Copyleft 2017-2025 by The Mojon Twins

#asm
	.pal_general
		ld  b, 0x7f
		ld  a, 0
		out (c), a
		ld  a, 0x45	// 0b0100000 OR 5 (FFFF0080)
		out (c), a
		ld  a, 1
		out (c), a
		ld  a, 0x4E	// 0b0100000 OR E (FFFF8000)
		out (c), a
		ld  a, 2
		out (c), a
		ld  a, 0x43	// 0b0100000 OR 3 (FFFFFF80)
		out (c), a
		ld  a, 3
		out (c), a
		ld  a, 0x54	// 0b0100000 OR 14 (FF000000)
		out (c), a
		ret
#endasm

