// MTE MK1 v4.10
// Copyleft 2010-2013, 2020-2024 by The Mojon Twins

// pantallas.h
// Includes the binary of the aplib-compressed static screens.
// title.bin, marco.bin (if suited) and ending.bin should be
// in the same directory.

extern unsigned char s_title [];
extern unsigned char s_marco [];
extern unsigned char s_ending [];

#asm
	._s_title
		BINARY "title.bin"
	._s_marco
#endasm
#ifndef DIRECT_TO_PLAY
#asm
		BINARY "marco.bin"
#endasm
#endif
#asm
	._s_ending
		BINARY "ending.bin"
#endasm

void unpack (void) {
	#asm
			call blackout

			ld hl, (_asm_int)
			ld de, 16384
		#ifdef DECOMPRESSOR_ZX0
			jp dzx0_standard
		#else
			jp depack
		#endif

		.blackout
			ld hl, 22528
			ld de, 22529
			ld bc, 767
			xor a
			ld (hl), a
			ldir
			ret
	#endasm
}

// Strings 

#asm 
	.str_controls
		defm "1 POAQ    %2 KEMPSTON%3 SINCLAIR"
		defb 0
	.str_copyright
		defm  "@ 2012, 2025 THE MOJON TWINS"
		defb 0
	.str_ending
		defm "SOY RICO POTRICO"
		defb 0
	.str_gameover
		defm "GAME OVER!"
		defb 0
#endasm

void title_screen (void) {
	#asm 
		call SPUpdateNow
	#endasm
	asm_int = (unsigned int) (s_title); unpack ();

	/*
	draw_text (11, 11, 71, "1 POAQ    %2 KEMPSTON%3 SINCLAIR");
	draw_text (2, 17, 67, "@ 2012, 2024 THE MOJON TWINS");
	*/

	#asm 
		ld  a, 11
		ld  (__x), a 
		ld  (__t), a 			// Because it is a multi line print		
		ld  (__y), a 
		ld  a, 71
		ld  (__n), a 
		ld  hl, str_controls
		call draw_text_loop

		ld  a, 2
		ld  (__x), a 
		ld  a, 17
		ld  (__y), a 
		ld  a, 67
		ld  (__n), a 
		ld  hl, str_copyright
		call draw_text_loop

		call SPUpdateNow
	#endasm

	if (is128k) {
		wyz_play_music (0);
	} else {
		#asm
			; Music generated by beepola

			call musicstart
		#endasm
	}
	
	while (1) {
		rand ();

		if (sp_KeyPressed (key_1)) {
			joyfunc = sp_JoyKeyboard; break;
		} else if (sp_KeyPressed (key_2)) {
			joyfunc = sp_JoyKempston; break;
		} else if (sp_KeyPressed (key_3)) {
			joyfunc = sp_JoySinclair1; break;
		}			
	}

	after_title:
	wyz_play_music (8);
	recuadrius ();
}

void game_ending (void) {
	#asm 
		call SPUpdateNow
	#endasm
	asm_int = (unsigned int) (s_ending); unpack ();

	//draw_text (8, 7, 4, "SOY RICO POTRICO");

	#asm 
		ld  a, 8
		ld  (__x), a 
		ld  a, 7
		ld  (__y), a 
		ld  a, 4
		ld  (__n), a 
		ld  hl, str_ending
		call draw_text_loop

		call SPUpdateNow
	#endasm

	wyz_play_music (9);
	espera_activa (9999);
	wyz_play_music (8);
}

void game_over (void) {
	wyz_play_music (8);

	#asm
			call SPUpdateNow
			call _sprite_remove_aid
			call _recuadrius

			ld  a, 11
			ld  (__x), a 
			ld  a, 14
			ld  (__y), a 
			ld  a, 7
			ld  (__n), a 
			ld  hl, str_gameover
			call draw_text_loop

			ld hl, _pokemon_tiles
			call _set_ts

			xor a 
			ld  (_rda), a 		// offset			
			
			// Paint
			ld  a, 6
			ld  (_psk), a
			ld  a, 12
			ld  (__x), a 
			ld  a, 8
			ld  (__y), a 
			ld  a, 3
			ld  (__n), a 

			call _pk_portrait
			
			halt
			call SPUpdateNow

			halt
	#endasm

	wyz_play_music (7);

	rdb = ay_counter;
	rdc = 32; 			// Skip # notes before dance!
	
	pti = any_key (); while (1) {

		#asm
			.gameover_loop
				ld  a, (_rdb) 
				ld  c, a 
				ld  a, (_ay_counter);
				cp  c 
				jr  z, gameover_animate_done 			// No new note

				ld  (_rdb), a 					// Update local counter

			.gameover_animate

				// Erase
				ld  a, (_rda)
				ld  c, a 
				
				ld  a, 6
				ld  (_psk), a
				ld  a, 12
				sub c
				ld  (__x), a 
				ld  a, 8
				ld  (__y), a 
				ld  a, 2
				ld  (__n), a 

				call _pk_portrait

				// Flip Flop dx
				ld  a, (_rda)
				ld  c, a 

				ld  a, (_rdc)
				or  a 
				jr  z, gameover_animate_do

				dec a 
				ld  (_rdc), a 
				jr  gameover_animate_paint
				
			.gameover_animate_do
				ld  a, 1
				sub c 
				ld  (_rda), a 
				ld  c, a 

			.gameover_animate_paint

				// Paint
				ld  a, 6
				ld  (_psk), a
				ld  a, 12
				sub c
				ld  (__x), a 
				ld  a, 8
				ld  (__y), a 
				ld  a, 3
				ld  (__n), a 

				call _pk_portrait

				call SPUpdateNow
			.gameover_animate_done
				halt

		#endasm
	
		ptj = any_key (); if (ptj && pti == 0) { break; } pti = ptj;
	}

	wyz_play_music (8);

	#asm
		ld hl, _tilesetc
		call _set_ts
		call _recuadrius
	#endasm

}