// MTE MK1 v4.8
// Copyleft 2010-2013, 2020-2021 by The Mojon Twins

// pantallas.h
// Includes the binary of the aplib-compressed static screens.
// title.bin, marco.bin (if suited) and ending.bin should be
// in the same directory.

extern unsigned char s_title [];
extern unsigned char s_marco [];
extern unsigned char s_ending [];

#asm
	._s_title
		BINARY "title.bin"
	._s_marco
#endasm
#ifndef DIRECT_TO_PLAY
#asm
		BINARY "marco.bin"
#endasm
#endif
#asm
	._s_ending
		BINARY "ending.bin"
#endasm

void unpack (void) {
	#asm
			call blackout

			ld hl, (_asm_int)
			ld de, 16384
		#ifdef DECOMPRESSOR_ZX0
			jp dzx0_standard
		#else
			jp depack
		#endif

		.blackout
			ld hl, 22528
			ld de, 22529
			ld bc, 767
			xor a
			ld (hl), a
			ldir
			ret
		#endasm
}

void title_screen (void) {
	if (color_selected == 0) {
		color_selected = 1;

		#ifdef LANG_EN
			draw_text (11, 11, 70, "1 ORIGINAL");
			draw_text (11, 13, 70, "2 COLOURED");
		#else
			draw_text (11, 11, 70, "1 ORIGINAL");
			draw_text (11, 13, 70, "2 COLORIN");
		#endif
		#asm 
			call SPUpdateNow
		#endasm
		
		while (1) {
			if (sp_KeyPressed (key_1)) {
				#asm
					ld  hl, attrs1
					ld  de, _tileset + 2048
					call dzx0_standard
				#endasm
				break;
			} else if (sp_KeyPressed (key_2)) {
				#asm
					ld  hl, attrs2
					ld  de, _tileset + 2048
					call dzx0_standard
				#endasm
				break;
			}
		}
	}

	#asm 
		call SPUpdateNow
	#endasm
	asm_int = (unsigned int) (s_title); unpack ();

	// CUSTOM {
	#ifdef LANG_EN
		draw_text (7, 4, 71, "RAMIRO, EL VAMPIRO");
		draw_text (9, 7, 7,  "AND THE MYSTERY");
		draw_text (9, 8, 7, "OF THE PAPYRUS");
	#else
		draw_text (7, 4, 71, "RAMIRO, EL VAMPIRO");
		draw_text (9, 7, 7, "EN EL MISTERIO");
		draw_text (11, 8, 7, "DEL PAPIRO");
	#endif

	/*
	draw_text (6, 4, 71, "RAMIRE, THE VAMPIRE");
	draw_text (12, 7, 7, "PUTS BACK");
	draw_text (11, 8, 7, "THE ZAPHIRE");
	*/
	
	draw_text (8, 19, 71, "MOJON TWINS 2023");
	draw_text (10, 20, 7, "CHURRERA 4.8");
	
	sp_UpdateNow ();
	// } END_OF_CUSTOM

	if (is128k) {
		arkos_play_music (0);
	} else {
		#asm
			; Music generated by beepola

			di
			call musicstart

		#endasm
	}
	
	while (1) {
		rda = rand ();	// This makes RNG randomer
		if (sp_KeyPressed (key_1)) {
			joyfunc = sp_JoyKeyboard; break;
		} else if (sp_KeyPressed (key_2)) {
			joyfunc = sp_JoyKempston; break;
		} else if (sp_KeyPressed (key_3)) {
			joyfunc = sp_JoySinclair1; break;
		}			
	}

	if (is128k) {
		arkos_stop_sound ();
	} 

	#asm
		; Recalculate tables!
		call SProtatetblInitialize 
		ei
	#endasm 
	after_title:
}

void game_ending (void) {
	#asm 
		call SPUpdateNow
	#endasm
	asm_int = (unsigned int) (s_ending); unpack ();

	// CUSTOM { 
	draw_text (7, 15, 7, "EL VAMPIRO RAMIRO");
	draw_text (8, 17, 7, "NUNCA GANA . . .");

	if (flags [16] < 99) {
		draw_text (9, 20, 5, "COMPLETADO   /");
		draw_2_digits (20, 20, flags [16] + 1);
	} else {
		draw_text (9, 20, 5, "COMPLETADO 100/");
	}

	sp_UpdateNow ();
	// } END OF CUSTOM

	if (is128k) {
		arkos_play_music (4);
	} else {
		beepet (); play_sfx (11);
	}
	espera_activa (500);

	if (is128k) arkos_stop_sound ();
}

void game_over (void) {
	//10, 11, 21, 13, GAME_OVER_ATTR
	#asm
			ld  a, 10
			ld  (__x), a
			ld  a, 11
			ld  (__y), a
			ld  a, 21
			ld  (__x2), a
			ld  a, 13
			ld  (__y2), a
			ld  a, GAME_OVER_ATTR
			ld  (__t), a
	#endasm
	draw_rectangle ();		
	draw_text (11, 12, GAME_OVER_ATTR, "GAME OVER!");
	#asm 
		call SPUpdateNow
	#endasm

	if (is128k) {
		arkos_play_music (3);
	} else {
		beepet (); play_sfx (10);
	}
	espera_activa (500);
	
	if (is128k) arkos_stop_sound ();
}
