// CPC Palette with HW values
// Generated by mkts_om v0.6.20210822
// Copyleft 2017-2021 by The Mojon Twins

const unsigned char my_inks [] = {
	0x18, // FF800080
	0x15, // FF0000FF
	0x04, // FF000080
	0x06, // FF008080
	0x13, // FF00FFFF
	0x0B, // FFFFFFFF
	0x02, // FF00FF80
	0x12, // FF00FF00
	0x16, // FF008000
	0x1A, // FF80FF00
	0x0A, // FFFFFF00
	0x00, // FF808080
	0x0E, // FFFF8000
	0x0C, // FFFF0000
	0x1C, // FF800000
	0x14  // FF000000
};

