// CPC Palette with HW values
// Generated by mkts_om v0.6.20210822
// Copyleft 2017-2021 by The Mojon Twins

const unsigned char my_inks [] = {
	0x13, // FF00FFFF
	0x0D, // FFFF00FF
	0x14, // FF000000
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B, // FFFFFFFF
	0x0B  // FFFFFFFF
};

