// MTE MK1 (la Churrera) v4
// Copyleft 2010-2014, 2020-2025 by the Mojon Twins

// Generated by ene2h.exe from ..\enems\enems.ene
// Copyleft 2010, 2017, 2020-2025 by The Mojon Twins

typedef struct {
	unsigned char x, y;
	unsigned char xy1, xy2;
	signed char mx, my;
	signed char t;
#if defined PLAYER_CAN_FIRE || defined ENABLE_SWORD
	unsigned char life;
#endif
} MALOTE;

MALOTE malotes [] = {
	// Pantalla 0
 	{112, 16, 0x11, 0xD8, 1, 0, 14},

	// Pantalla 1
 	{48, 32, 0x11, 0xD8, 2, 0, 11},
 	{80, 96, 0x56, 0x88, 2, 2, 7},

	// Pantalla 2
 	{144, 16, 0x91, 0xC3, 2, 2, 8},
 	{80, 16, 0x11, 0xD8, 1, 0, 14},

	// Pantalla 3
 	{144, 16, 0x11, 0xD8, 0, 1, 12},
 	{16, 128, 0x11, 0xD8, 0, -1, 12},

	// Pantalla 4

	// Pantalla 5

	// Pantalla 6
 	{128, 32, 0x82, 0xD2, 1, 0, 2},
 	{80, 128, 0x58, 0xC8, 2, 0, 2},

	// Pantalla 7
 	{96, 32, 0x62, 0xC2, 1, 0, 1},
 	{16, 64, 0x14, 0x64, 2, 0, 4},

	// Pantalla 8
 	{128, 96, 0x86, 0xC6, 1, 0, 2},
 	{208, 112, 0x11, 0xD8, -1, 0, 12},

	// Pantalla 9
 	{80, 112, 0x57, 0x97, 1, 0, 2},
 	{144, 80, 0x11, 0xD8, 0, 1, 12},

	// Pantalla 10
 	{16, 16, 0x11, 0xD1, 1, 0, 2},
 	{176, 64, 0x14, 0xB4, -1, 0, 2},

	// Pantalla 11
 	{16, 48, 0x13, 0x48, 2, 2, 10},
 	{192, 64, 0x74, 0xC8, -2, 2, 8},

	// Pantalla 12
 	{80, 16, 0x41, 0x51, 0, 0, 3},
 	{208, 96, 0x66, 0xD6, -1, 0, 2},

	// Pantalla 13
 	{32, 80, 0x25, 0xC5, 2, 0, 3},
 	{160, 32, 0x11, 0xD8, -1, 1, 12},

	// Pantalla 14
 	{176, 16, 0xB1, 0xB4, 0, 2, 1},
 	{176, 64, 0x11, 0xD8, -1, 0, 14},

	// Pantalla 15
 	{96, 112, 0x11, 0xD8, 2, 0, 14},
 	{80, 16, 0x11, 0x53, -2, 2, 8},

	// Pantalla 16
 	{160, 96, 0xA6, 0xD6, 1, 0, 2},
 	{80, 32, 0x52, 0x77, 1, 1, 8},

	// Pantalla 17
 	{160, 16, 0xA1, 0xB6, 2, 2, 7},

	// Pantalla 18
 	{32, 64, 0x24, 0xD6, 2, 2, 10},

	// Pantalla 19
 	{176, 80, 0x65, 0xB5, -2, 0, 3},
 	{64, 112, 0x47, 0xD7, 1, 0, 2},

	// Pantalla 20
 	{192, 112, 0x67, 0xC7, -2, 0, 3},
 	{144, 48, 0x11, 0xD8, 1, 0, 12},

	// Pantalla 21
 	{48, 32, 0x32, 0x48, 1, 1, 8},
 	{80, 64, 0x11, 0xD8, 1, 0, 11},

	// Pantalla 22
 	{32, 64, 0x11, 0xD8, 0, 1, 11},
 	{160, 16, 0x11, 0xD8, 0, 2, 11},

	// Pantalla 23
 	{16, 112, 0x11, 0xD8, 1, 0, 11},
 	{144, 80, 0x11, 0xD8, 0, 1, 11},

	// Pantalla 24
 	{80, 16, 0x51, 0xC2, 1, 1, 8},
 	{96, 80, 0x11, 0xD8, 1, 0, 12},

	// Pantalla 25
 	{48, 16, 0x31, 0x45, 2, 2, 8},

	// Pantalla 26
 	{80, 96, 0x56, 0xC6, 2, 0, 3},
 	{208, 64, 0x14, 0xD4, -1, 0, 2},

	// Pantalla 27
 	{48, 96, 0x36, 0xC6, 2, 0, 3},
 	{80, 16, 0x11, 0xD8, 0, 1, 12},

	// Pantalla 28
 	{48, 112, 0x37, 0xD7, 1, 0, 8},

	// Pantalla 29
 	{64, 80, 0x45, 0x87, 1, 1, 8},
 	{48, 16, 0x11, 0xD8, 0, 2, 12},

	// Pantalla 30
 	{112, 128, 0x11, 0xD8, 0, -1, 12},

	// Pantalla 31

	// Pantalla 32
 	{112, 16, 0x11, 0xD8, 0, 1, 12},
 	{64, 80, 0x11, 0xD8, 0, -1, 11},

	// Pantalla 33
 	{16, 96, 0x16, 0xA8, 2, 2, 8},
 	{192, 16, 0xA1, 0xC5, -1, 1, 8},

	// Pantalla 34
 	{112, 112, 0x73, 0x77, 0, -2, 3},
 	{176, 16, 0x11, 0xD8, 0, 1, 11},

	// Pantalla 35
 	{208, 128, 0x11, 0xD8, 0, -2, 13},

	// Pantalla 36
 	{128, 16, 0x11, 0xD8, 2, 0, 13},
 	{48, 128, 0x11, 0xD8, 0, -1, 13},

	// Pantalla 37
 	{112, 48, 0x11, 0xD8, 2, 0, 12},
 	{64, 96, 0x11, 0xD8, 0, 2, 12},

	// Pantalla 38
 	{48, 16, 0x11, 0xD8, 0, 2, 12},
 	{144, 96, 0x11, 0xD8, 2, 0, 12},

	// Pantalla 39

	// Pantalla 40

	// Pantalla 41

	{0xff}
};

// enoffs index, contains enoffs for each screen
unsigned char enoffs_index [] = {
	0, 1, 3, 5, 7, 7, 7, 
	9, 11, 13, 15, 17, 19, 21, 
	23, 25, 27, 29, 30, 31, 33, 
	35, 37, 39, 41, 43, 44, 46, 
	48, 49, 51, 52, 52, 54, 56, 
	58, 59, 61, 63, 65, 65, 65, 
	65 // <- total number of enems to make coding easier
};

#define N_ENEMS_TYPE_0 61
#define N_ENEMS_TYPE_1 2
#define N_ENEMS_TYPE_2 10
#define N_ENEMS_TYPE_3 7
#define N_ENEMS_TYPE_5 0
#define N_ENEMS_TYPE_6 0
#define N_ENEMS_TYPE_7 2
#define N_ENEMS_TYPE_8 11
#define N_ENEMS_TYPE_10 2
#define N_ENEMS_TYPE_11 8
#define N_ENEMS_TYPE_12 15
#define N_ENEMS_TYPE_13 3
#define N_ENEMS_TYPE_14 4

// This is output the way it worked originally, please modify if you need
// You may want to add type 5 or 6's below.
#define BADDIES_COUNT (N_ENEMS_TYPE_1+N_ENEMS_TYPE_2+N_ENEMS_TYPE_3)

#define TOTAL_EXISTING_ENEMS 65

typedef struct {
	unsigned char xy, tipo, act;
} HOTSPOT;

HOTSPOT hotspots [] = {
	{36, 3, 0}, 
	{113, 1, 0}, 
	{194, 1, 0}, 
	{209, 3, 0}, 
	{100, 2, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{86, 1, 0}, 
	{165, 1, 0}, 
	{86, 1, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{53, 3, 0}, 
	{0, 0, 0}, 
	{162, 1, 0}, 
	{86, 1, 0}, 
	{180, 1, 0}, 
	{18, 3, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{19, 1, 0}, 
	{72, 1, 0}, 
	{181, 1, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{83, 3, 0}, 
	{131, 1, 0}, 
	{166, 1, 0}, 
	{147, 3, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{99, 3, 0}, 
	{113, 12, 0}, 
	{97, 12, 0}, 
	{216, 3, 0}, 
	{120, 12, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}
};

#define N_HOTSPOTS_TYPE_0 17
#define N_HOTSPOTS_TYPE_1 13
#define N_HOTSPOTS_TYPE_2 1
#define N_HOTSPOTS_TYPE_3 8
#define N_HOTSPOTS_TYPE_4 0
#define N_HOTSPOTS_TYPE_5 0
#define N_HOTSPOTS_TYPE_6 0
#define N_HOTSPOTS_TYPE_7 0
#define N_HOTSPOTS_TYPE_12 3

