// MTE MK1 (la Churrera) v4
// Copyleft 2010-2014, 2020-2025 by the Mojon Twins

// Generated by ene2h.exe from empty=10,2,3
// Copyleft 2010, 2017, 2020-2025 by The Mojon Twins

typedef struct {
	unsigned char x, y;
	unsigned char xy1, xy2;
	signed char mx, my;
	signed char t;
#if defined PLAYER_CAN_FIRE || defined ENABLE_SWORD
	unsigned char life;
#endif
} MALOTE;

MALOTE malotes [] = {
	// Pantalla 0
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 1
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 2
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 3
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 4
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 5
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 6
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 7
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 8
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 9
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 10
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 11
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 12
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 13
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 14
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 15
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 16
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 17
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 18
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},

	// Pantalla 19
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0},
 	{0, 0, 0x00, 0x00, 0, 0, 0}

};

#define N_ENEMS_TYPE_0 60
#define N_ENEMS_TYPE_1 0
#define N_ENEMS_TYPE_2 0
#define N_ENEMS_TYPE_3 0
#define N_ENEMS_TYPE_5 0
#define N_ENEMS_TYPE_6 0
#define N_ENEMS_TYPE_7 0

// This is output the way it worked originally, please modify if you need
// You may want to add type 5 or 6's below.
#define BADDIES_COUNT (N_ENEMS_TYPE_1+N_ENEMS_TYPE_2+N_ENEMS_TYPE_3)

#define TOTAL_EXISTING_ENEMS 60

typedef struct {
	unsigned char xy, tipo, act;
} HOTSPOT;

HOTSPOT hotspots [] = {
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}
};

#define N_HOTSPOTS_TYPE_0 20
#define N_HOTSPOTS_TYPE_1 0
#define N_HOTSPOTS_TYPE_2 0
#define N_HOTSPOTS_TYPE_3 0
#define N_HOTSPOTS_TYPE_4 0
#define N_HOTSPOTS_TYPE_5 0
#define N_HOTSPOTS_TYPE_6 0
#define N_HOTSPOTS_TYPE_7 0

