// CPC Palette with HW values
// Generated by mkts_om v0.11.20250501
// Copyleft 2017-2025 by The Mojon Twins

const unsigned char my_inks [] = {
	0x18, // FF800080
	0x14, // FF000000
	0x0B, // FFFFFFFF
	0x04, // FF000080
	0x17, // FF0080FF
	0x13, // FF00FFFF
	0x06, // FF008080
	0x12, // FF00FF00
	0x16, // FF008000
	0x1A, // FF80FF00
	0x0A, // FFFFFF00
	0x03, // FFFFFF80
	0x0E, // FFFF8000
	0x0C, // FFFF0000
	0x1C, // FF800000
	0x00  // FF808080
};

