// MTE MK1 (la Churrera) v4
// Copyleft 2010-2014, 2020, 2021 by the Mojon Twins

// Generated by ene2h.exe from ..\src\enems\enems.ene
// Copyleft 2010, 2017, 2020, 2021 by The Mojon Twins

typedef struct {
	unsigned char x, y;
	unsigned char xy1, xy2;
	signed char mx, my;
	signed char t;
#if defined PLAYER_CAN_FIRE || defined ENABLE_SWORD
	unsigned char life;
#endif
} MALOTE;

MALOTE malotes [] = {
	// Pantalla 0
 	{16, 32, 0x12, 0x38, 2, 2, 3},
 	{160, 16, 0xA1, 0xA8, 0, 1, 1},
 	{176, 128, 0xB1, 0xB8, 0, -1, 2},

	// Pantalla 1
 	{128, 128, 0x18, 0x88, -1, 0, 4},
 	{144, 16, 0x91, 0x95, 0, 1, 2},
 	{48, 16, 0x31, 0x35, 0, 1, 3},

	// Pantalla 2
 	{128, 16, 0x81, 0xA3, 2, 2, 7},
 	{128, 80, 0x85, 0x88, 0, 1, 2},
 	{32, 48, 0x23, 0x38, 1, 1, 3},

	// Pantalla 3
 	{16, 112, 0x17, 0x77, 1, 0, 3},
 	{128, 112, 0x87, 0xC7, 1, 0, 2},
 	{176, 128, 0x28, 0xB8, -1, 0, 4},

	// Pantalla 4
 	{208, 16, 0xD1, 0xD8, 0, 1, 1},
 	{128, 80, 0x83, 0x85, 0, -1, 2},
 	{16, 112, 0x17, 0x47, 1, 0, 4},

	// Pantalla 5
 	{96, 48, 0x61, 0x83, 2, -2, 10},
 	{144, 48, 0x93, 0xD7, 2, 2, 3},
 	{16, 112, 0x17, 0x77, 1, 0, 4},

	// Pantalla 6
 	{176, 64, 0x34, 0xB5, -2, 2, 3},
 	{48, 32, 0x32, 0xD2, 1, 0, 4},
 	{208, 112, 0x27, 0xD7, -1, 0, 2},

	// Pantalla 7
 	{128, 128, 0x81, 0x88, 0, -1, 3},
 	{160, 32, 0xA2, 0xA8, 0, 1, 2},
 	{48, 32, 0x31, 0x32, 0, 0, 4},

	// Pantalla 8
 	{176, 16, 0x31, 0xB3, -2, 2, 8},
 	{48, 48, 0x31, 0xB3, 2, -2, 7},
 	{64, 80, 0x45, 0x96, 2, 2, 10},

	// Pantalla 9
 	{208, 128, 0xD1, 0xD8, 0, -1, 3},
 	{48, 96, 0x36, 0x96, 1, 0, 2},
 	{96, 16, 0x21, 0x63, -2, 2, 9},

	// Pantalla 10
 	{208, 48, 0x43, 0xD3, -1, 0, 1},
 	{16, 96, 0x16, 0xC6, 1, 0, 2},
 	{16, 16, 0x11, 0x21, 0, 0, 3},

	// Pantalla 11
 	{32, 16, 0x21, 0xC8, 2, 2, 3},
 	{160, 16, 0x11, 0xA6, -1, 1, 1},
 	{208, 48, 0x83, 0xD8, -1, 1, 3},

	// Pantalla 12
 	{32, 32, 0x22, 0x46, 1, 1, 1},
 	{160, 16, 0x51, 0xA2, -1, 1, 2},
 	{160, 48, 0xA3, 0xC7, 2, 2, 3},

	// Pantalla 13
 	{32, 16, 0x21, 0xC8, 2, 2, 7},
 	{192, 16, 0x21, 0xC8, -2, 2, 8},
 	{64, 96, 0x43, 0x96, 2, -2, 9},

	// Pantalla 14
 	{208, 16, 0x11, 0xD1, -2, 0, 3},
 	{16, 112, 0x17, 0xB7, 2, 0, 3},
 	{96, 48, 0x13, 0x63, -1, 0, 4},

	// Pantalla 15
 	{16, 32, 0x12, 0x17, 0, 2, 3},
 	{112, 16, 0x71, 0x76, 0, 1, 2},
 	{160, 48, 0xA3, 0xA7, 0, 1, 4},

	// Pantalla 16
 	{128, 16, 0x81, 0x88, 0, 2, 1},
 	{96, 16, 0x61, 0x68, 0, 2, 2},
 	{16, 64, 0x14, 0x67, 1, 1, 3},

	// Pantalla 17
 	{32, 32, 0x22, 0xC2, 1, 0, 1},
 	{160, 48, 0xA3, 0xC8, 2, 2, 2},
 	{176, 112, 0x27, 0xB8, -1, 1, 3},

	// Pantalla 18
 	{48, 32, 0x32, 0x93, 1, 1, 2},
 	{144, 112, 0x37, 0x97, -1, 0, 4},
 	{16, 16, 0x11, 0x18, 0, 1, 1},

	// Pantalla 19
 	{48, 16, 0x31, 0x55, 1, 1, 1},
 	{32, 80, 0x25, 0x35, 1, 0, 2},
 	{32, 112, 0x27, 0x27, 0, 0, 4},

	// Pantalla 20
 	{128, 128, 0x24, 0x88, -2, -2, 8},
 	{32, 64, 0x24, 0x88, 2, 2, 10},
 	{208, 112, 0xD1, 0xD7, 0, -1, 4},

	// Pantalla 21
 	{16, 128, 0x11, 0x68, 2, -2, 2},
 	{192, 16, 0xC1, 0xC8, 0, 1, 1},
 	{160, 128, 0xA3, 0xA8, 0, -1, 3},

	// Pantalla 22
 	{32, 16, 0x21, 0x68, 1, 1, 4},
 	{128, 16, 0x81, 0x88, 0, 1, 2},
 	{192, 16, 0xC1, 0xC7, 0, 1, 3},

	// Pantalla 23
 	{32, 112, 0x27, 0xD7, 1, 0, 4},
 	{208, 80, 0xD1, 0xD5, 0, -1, 1},
 	{112, 32, 0x12, 0x72, -1, 0, 2},

	// Pantalla 24
 	{112, 112, 0x17, 0x77, -1, 0, 2},
 	{32, 80, 0x21, 0x25, 0, -1, 4},
 	{80, 80, 0x52, 0x55, 0, -1, 2}

};

#define N_ENEMS_TYPE_0 0
#define N_ENEMS_TYPE_1 11
#define N_ENEMS_TYPE_2 20
#define N_ENEMS_TYPE_3 19
#define N_ENEMS_TYPE_5 0
#define N_ENEMS_TYPE_6 0
#define N_ENEMS_TYPE_7 3
#define N_ENEMS_TYPE_8 3
#define N_ENEMS_TYPE_9 2
#define N_ENEMS_TYPE_10 3

// This is output the way it worked originally, please modify if you need
// You may want to add type 5 or 6's below.
#define BADDIES_COUNT (N_ENEMS_TYPE_1+N_ENEMS_TYPE_2+N_ENEMS_TYPE_3)

typedef struct {
	unsigned char xy, tipo, act;
} HOTSPOT;

HOTSPOT hotspots [] = {
	{17, 2, 0}, 
	{85, 1, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{113, 1, 0}, 
	{0, 0, 0}, 
	{151, 1, 0}, 
	{177, 1, 0}, 
	{98, 1, 0}, 
	{214, 1, 0}, 
	{209, 1, 0}, 
	{0, 0, 0}, 
	{212, 1, 0}, 
	{210, 1, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{72, 2, 0}, 
	{49, 1, 0}, 
	{114, 1, 0}, 
	{23, 1, 0}, 
	{102, 1, 0}, 
	{210, 2, 0}, 
	{130, 1, 0}, 
	{0, 0, 0}
};

#define N_HOTSPOTS_TYPE_0 8
#define N_HOTSPOTS_TYPE_1 14
#define N_HOTSPOTS_TYPE_2 3
#define N_HOTSPOTS_TYPE_3 0
#define N_HOTSPOTS_TYPE_4 0
#define N_HOTSPOTS_TYPE_5 0
#define N_HOTSPOTS_TYPE_6 0
#define N_HOTSPOTS_TYPE_7 0

