// MTE MK1 (la Churrera) v4
// Copyleft 2010-2014, 2020-2025 by the Mojon Twins

// Generated by ene2h.exe from ..\enems\enems.ene
// Copyleft 2010, 2017, 2020-2025 by The Mojon Twins

typedef struct {
	unsigned char x, y;
	unsigned char xy1, xy2;
	signed char mx, my;
	signed char t;
#if ((defined PLAYER_CAN_FIRE || defined ENABLE_SWORD) && ENEMS_LIFE_GAUGE > 1) || defined FORCE_ENEMS_LIFE
	unsigned char life;
#endif
} MALOTE;

MALOTE malotes [] = {
	// Pantalla 0
 	{64, 16, 0x41, 0x48, 0, 4, 3},
 	{208, 16, 0x61, 0xD1, -2, 0, 1},
 	{192, 0, 0x70, 0xC0, -2, 0, 1},

	// Pantalla 1
 	{128, 0, 0x80, 0x84, 0, 1, 2},
 	{144, 16, 0x91, 0xB6, 2, 2, 2},
 	{96, 0, 0x60, 0x62, 0, 1, 2},

	// Pantalla 2
 	{16, 32, 0x12, 0x62, 2, 0, 1},
 	{144, 96, 0x90, 0x96, 0, -1, 3},
 	{176, 0, 0xB0, 0xB5, 0, 1, 2},

	// Pantalla 3
 	{96, 112, 0x37, 0x67, -1, 0, 3},
 	{48, 0, 0x30, 0x32, 0, 1, 1},
 	{208, 0, 0xD0, 0xD4, 0, 2, 1},

	// Pantalla 4
 	{64, 0, 0x40, 0x45, 0, 1, 1},
 	{96, 0, 0x60, 0x64, 0, 1, 1},
 	{160, 0, 0xA0, 0xD5, 2, 2, 2},

	// Pantalla 5
 	{80, 112, 0x17, 0x57, -2, 0, 2},
 	{96, 0, 0x00, 0x60, -1, 0, 2},
 	{224, 0, 0xE0, 0xE3, 0, 1, 2},

	// Pantalla 6
 	{128, 16, 0x81, 0x88, 0, 2, 3},
 	{160, 16, 0xA1, 0xA6, 0, 1, 1},
 	{16, 96, 0x16, 0x58, 4, 4, 2},

	// Pantalla 7
 	{16, 80, 0x13, 0x65, 1, -1, 1},
 	{16, 16, 0x11, 0x61, 2, 0, 2},
 	{160, 0, 0xA0, 0xA9, 0, 2, 3},

	// Pantalla 8
 	{48, 32, 0x32, 0x92, 2, 0, 3},
 	{112, 48, 0x73, 0x78, 0, 1, 2},
 	{160, 96, 0xA0, 0xA6, 0, -2, 3},

	// Pantalla 9
 	{96, 128, 0x61, 0x68, 0, -2, 4},
 	{144, 16, 0x91, 0xB7, 2, 2, 3},
 	{112, 48, 0x21, 0x73, -2, -2, 1},

	// Pantalla 10
 	{64, 128, 0x48, 0xD8, 1, 0, 4},
 	{208, 112, 0x77, 0xD7, -1, 0, 1},
 	{64, 16, 0x41, 0x61, 1, 0, 3},

	// Pantalla 11
 	{16, 128, 0x18, 0xA8, 1, 0, 4},
 	{48, 112, 0x34, 0x37, 0, -1, 4},
 	{80, 48, 0x53, 0xA6, 2, 2, 2},

	// Pantalla 12
 	{208, 112, 0x87, 0xD7, -1, 0, 3},
 	{208, 80, 0xD1, 0xD5, 0, -1, 2},
 	{16, 16, 0x11, 0x68, 4, 4, 3},

	// Pantalla 13
 	{64, 0, 0x40, 0x73, 2, 2, 1},
 	{16, 64, 0x14, 0x57, 1, 1, 2},
 	{208, 16, 0xC1, 0xD8, -2, 2, 3},

	// Pantalla 14
 	{16, 0, 0x10, 0x72, 1, 1, 2},
 	{208, 0, 0xB0, 0xD3, -2, 2, 3},
 	{64, 64, 0x40, 0x64, 1, -1, 1},

	// Pantalla 15
 	{160, 112, 0xA4, 0xA7, 0, -1, 4},
 	{192, 32, 0x32, 0xC2, -1, 0, 4},
 	{64, 0, 0x40, 0xB1, 1, 1, 3},

	// Pantalla 16
 	{192, 48, 0x53, 0xC3, -1, 0, 4},
 	{112, 32, 0x72, 0xB2, 1, 0, 3},
 	{64, 80, 0x45, 0xC7, 2, 2, 2},

	// Pantalla 17
 	{192, 48, 0x23, 0xC3, -1, 0, 4},
 	{16, 32, 0x12, 0x82, 1, 0, 1},
 	{16, 64, 0x14, 0x77, 2, 2, 2},

	// Pantalla 18
 	{208, 64, 0x84, 0xD4, -1, 0, 2},
 	{48, 16, 0x31, 0x35, 0, 2, 1},
 	{64, 32, 0x42, 0x45, 0, 2, 3},

	// Pantalla 19
 	{16, 112, 0x17, 0x77, 1, 0, 1},
 	{192, 128, 0xC1, 0xC8, 0, -1, 4},
 	{112, 48, 0x13, 0x73, -2, 0, 3},

	// Pantalla 20
 	{176, 48, 0x23, 0xB3, -1, 0, 1},
 	{176, 64, 0x34, 0xB4, -1, 0, 1},
 	{16, 0, 0x10, 0xC2, 2, 2, 2},

	// Pantalla 21
 	{32, 112, 0x27, 0xC7, 2, 0, 4},
 	{192, 32, 0x32, 0xC2, -2, 0, 4},
 	{176, 80, 0x35, 0xB5, -1, 0, 1},

	// Pantalla 22
 	{208, 80, 0x25, 0xD5, -1, 0, 4},
 	{64, 64, 0x44, 0xB4, 1, 0, 2},
 	{16, 0, 0x00, 0x19, -3, 3, 2},

	// Pantalla 23
 	{16, 48, 0x13, 0xD3, 1, 0, 4},
 	{96, 64, 0x64, 0x68, 0, 1, 1},
 	{208, 80, 0x85, 0xD8, -2, 2, 3},

	// Pantalla 24
 	{96, 32, 0x62, 0x66, 0, 2, 1},
 	{128, 80, 0x85, 0xE5, 2, 0, 4},
 	{96, 112, 0x17, 0x67, -1, 0, 3},

	// Pantalla 25
 	{112, 16, 0x71, 0x75, 0, 1, 2},
 	{48, 96, 0x30, 0x36, 0, -2, 1},
 	{176, 48, 0xB3, 0xB8, 0, 2, 3},

	// Pantalla 26
 	{160, 32, 0xA2, 0xC5, 2, 2, 1},
 	{96, 48, 0x60, 0x63, 0, -1, 2},
 	{144, 144, 0x39, 0x99, -1, 0, 3},

	// Pantalla 27
 	{32, 80, 0x21, 0x25, 0, -2, 1},
 	{192, 80, 0xC2, 0xC5, 0, -2, 2},
 	{112, 80, 0x72, 0x75, 0, -1, 3},

	// Pantalla 28
 	{208, 48, 0x23, 0xD3, -1, 0, 4},
 	{64, 32, 0x42, 0xC2, 1, 0, 2},
 	{80, 96, 0x56, 0x76, 1, 0, 1},

	// Pantalla 29
 	{112, 16, 0x11, 0x75, -2, 2, 3},
 	{176, 64, 0xB4, 0xB6, 0, 1, 1},
 	{208, 80, 0xD5, 0xD8, 0, 1, 1}

};

// enoffs index, contains enoffs for each screen
unsigned char enoffs_index [] = {
	0, 3, 6, 9, 12, 15, 
	18, 21, 24, 27, 30, 33, 
	36, 39, 42, 45, 48, 51, 
	54, 57, 60, 63, 66, 69, 
	72, 75, 78, 81, 84, 87, 
	90 // <- total number of enems to make coding easier
};

#define N_ENEMS_TYPE_0 0
#define N_ENEMS_TYPE_1 27
#define N_ENEMS_TYPE_2 25
#define N_ENEMS_TYPE_3 23
#define N_ENEMS_TYPE_5 0
#define N_ENEMS_TYPE_6 0
#define N_ENEMS_TYPE_7 0

// This is output the way it worked originally, please modify if you need
// You may want to add type 5 or 6's below.
#define BADDIES_COUNT (N_ENEMS_TYPE_1+N_ENEMS_TYPE_2+N_ENEMS_TYPE_3)

#define TOTAL_EXISTING_ENEMS 90

typedef struct {
	unsigned char xy, tipo, act;
} HOTSPOT;

HOTSPOT hotspots [] = {
	{22, 2, 0}, 
	{115, 2, 0}, 
	{113, 1, 0}, 
	{200, 1, 0}, 
	{81, 1, 0}, 
	{24, 1, 0}, 
	{98, 1, 0}, 
	{115, 1, 0}, 
	{69, 1, 0}, 
	{129, 2, 0}, 
	{209, 2, 0}, 
	{18, 1, 0}, 
	{200, 1, 0}, 
	{100, 1, 0}, 
	{148, 1, 0}, 
	{34, 1, 0}, 
	{66, 1, 0}, 
	{209, 1, 0}, 
	{19, 1, 0}, 
	{113, 1, 0}, 
	{133, 1, 0}, 
	{35, 1, 0}, 
	{70, 1, 0}, 
	{87, 1, 0}, 
	{129, 1, 0}, 
	{87, 1, 0}, 
	{114, 1, 0}, 
	{100, 1, 0}, 
	{129, 1, 0}, 
	{212, 1, 0}
};

#define N_HOTSPOTS_TYPE_0 0
#define N_HOTSPOTS_TYPE_1 26
#define N_HOTSPOTS_TYPE_2 4
#define N_HOTSPOTS_TYPE_3 0
#define N_HOTSPOTS_TYPE_4 0
#define N_HOTSPOTS_TYPE_5 0
#define N_HOTSPOTS_TYPE_6 0
#define N_HOTSPOTS_TYPE_7 0

