// MTE MK1 (la Churrera) v4
// Copyleft 2010-2014, 2020-2025 by the Mojon Twins

// Generated by ene2h.exe from ..\enems\enems.ene
// Copyleft 2010, 2017, 2020-2025 by The Mojon Twins

typedef struct {
	unsigned char x, y;
	unsigned char xy1, xy2;
	signed char mx, my;
	signed char t;
#if ((defined PLAYER_CAN_FIRE || defined ENABLE_SWORD) && ENEMS_LIFE_GAUGE > 1) || defined FORCE_ENEMS_LIFE
	unsigned char life;
#endif
} MALOTE;

MALOTE malotes [] = {
	// Pantalla 0

	// Pantalla 1
 	{64, 64, 0x44, 0x94, 1, 0, 1},

	// Pantalla 2
 	{48, 32, 0x32, 0xA2, 1, 0, 3},

	// Pantalla 3
 	{160, 96, 0x56, 0xA6, -1, 0, 2},

	// Pantalla 4
 	{160, 112, 0x57, 0xA7, -1, 0, 3},
 	{80, 48, 0x53, 0x83, 1, 0, 2},

	// Pantalla 5
 	{112, 80, 0x55, 0x75, -1, 0, 2},

	// Pantalla 6
 	{64, 96, 0x46, 0x96, 1, 0, 3},

	// Pantalla 7
 	{48, 32, 0x32, 0x72, 1, 0, 2},
 	{32, 128, 0x28, 0x58, 1, 0, 3},

	// Pantalla 8

	// Pantalla 9

	// Pantalla 10

	// Pantalla 11

	// Pantalla 12

	// Pantalla 13

	// Pantalla 14

	// Pantalla 15

	// Pantalla 16

	// Pantalla 17

	// Pantalla 18

	// Pantalla 19

	// Pantalla 20

	// Pantalla 21

	// Pantalla 22

	// Pantalla 23

	// Pantalla 24

	// Pantalla 25

	// Pantalla 26

	// Pantalla 27

	// Pantalla 28

	// Pantalla 29

	// Pantalla 30

	// Pantalla 31

	// Pantalla 32

	// Pantalla 33

	// Pantalla 34

	// Pantalla 35

	// Pantalla 36

	// Pantalla 37

	// Pantalla 38

	// Pantalla 39

	{0xff}
};

// enoffs index, contains enoffs for each screen
unsigned char enoffs_index [] = {
	0, 0, 1, 2, 3, 5, 6, 7, 
	9, 9, 9, 9, 9, 9, 9, 9, 
	9, 9, 9, 9, 9, 9, 9, 9, 
	9, 9, 9, 9, 9, 9, 9, 9, 
	9, 9, 9, 9, 9, 9, 9, 9, 
	9 // <- total number of enems to make coding easier
};

#define N_ENEMS_TYPE_0 111
#define N_ENEMS_TYPE_1 1
#define N_ENEMS_TYPE_2 4
#define N_ENEMS_TYPE_3 4
#define N_ENEMS_TYPE_5 0
#define N_ENEMS_TYPE_6 0
#define N_ENEMS_TYPE_7 0

// This is output the way it worked originally, please modify if you need
// You may want to add type 5 or 6's below.
#define BADDIES_COUNT (N_ENEMS_TYPE_1+N_ENEMS_TYPE_2+N_ENEMS_TYPE_3)

#define TOTAL_EXISTING_ENEMS 9

typedef struct {
	unsigned char xy, tipo, act;
} HOTSPOT;

HOTSPOT hotspots [] = {
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}, 
	{0, 0, 0}
};

#define N_HOTSPOTS_TYPE_0 40
#define N_HOTSPOTS_TYPE_1 0
#define N_HOTSPOTS_TYPE_2 0
#define N_HOTSPOTS_TYPE_3 0
#define N_HOTSPOTS_TYPE_4 0
#define N_HOTSPOTS_TYPE_5 0
#define N_HOTSPOTS_TYPE_6 0
#define N_HOTSPOTS_TYPE_7 0

